trigger:
  batch: true
  branches:
    include:
    - main

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts (1)'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: 'hmcts-sandbox-agent-pool'
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: finops-reporting
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
    - plan
    - apply
    - destroy

  - name: environment_components
    type: object
    default:
    - deployment: 'finops_reporting_sbox'
      environment: 'sbox'
      component: 'logic-app'
      service_connection: 'DTS-SHAREDSERVICES-SBOX'
      storage_account_rg: 'finops-reporting-sbox-rg'
      storage_account_name: 'finopsreportingsbox'
      dependsOn: 'Precheck'
      pipeline_tests: false

stages:
  - stage: Precheck
    jobs:
      - job:
        pool:
          name: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'azurerm-sandbox'
              overrideAction: ${{ parameters.overrideAction }}


  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool: 
            name: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              overrideAction: ${{ parameters.overrideAction }}
              environment: ${{ deployment.environment }}
              serviceConnection: ${{ deployment.service_connection }}
              terraformInitSubscription: ${{ variables.terraformInitSubscription }}
              product: ${{ variables.product }}
              component: ${{ deployment.component }}