name: Balance Summery Export Cost Management API
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # Every weekday at 8pm UTC
  push:
    branches:
      - "t1"
permissions:
  id-token: write
# set vars for script here 
env: 
  sa_key: ${{ secrets.SA_KEY }}
  subscription_name: ${{ vars.SUBSCRIPTION_NAME }}
  client_id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
  subscription_id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
  tenant_id: ${{ vars.AZURE_TENANT_ID }}
  container_name: ${{ vars.CONTAINER_NAME }}
  resource_group: ${{ vars.RESOURCE_GROUP }}
  service_principal_app_id: ${{ vars.SERVICE_PRINCIPAL_APP_ID }}
  storage_account_name: ${{ vars.STORAGE_ACCOUNT_NAME }}
  billing_account: ${{ vars.BILLING_ACCOUNT }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Balance Summary Export
        run: .github/workflows/bash-scripts/balance_summary_export.sh