name: Cost Management API
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # Every weekday at 8pm UTC
permissions:
  id-token: write
# set vars for script here 
env: 
  subscription_name: DTS-SHAREDSERVICES-SBOX
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set the value in bash
        id: step_one
        run: |
          echo "current dir:" 
          pwd
          echo "whats in that dir:"
          ls -R
          
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: Cost Management API
      #   run: .github/workflows/bash-scripts/balance_summary_export.sh