name: Cost Management API
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # Every weekday at 8pm UTC
permissions:
  id-token: write
# set vars for script here 
env: 
  subscription_name: ${{ secrets.SUBSCRIPTION_NAME }}
  client_id: ${{ secrets.AZURE_CLIENT_ID }}
  subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  container_name: ${{ secrets.CONTAINER_NAME }}
  resource_group: ${{ secrets.RESOURCE_GROUP }}
  service_principal_app_id: ${{ secrets.SERVICE_PRINCIPAL_APP_ID }}
  storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  billing_account: ${{ secrets.SUBSCRIPTION_NAME }}
  # : ${{ secrets.SUBSCRIPTION_NAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set the value in bash
        run: |
          echo "current dir:" 
          pwd
          echo "whats in that dir:"
          ls -R
   
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Cost Management Export
        run: .github/workflows/bash-scripts/cost_management_export.sh